export function renderScaffoldUsage(): string {
  return [
    'Memorize — shared project memory for human + AI collaboration',
    '',
    'Day-to-day:',
    '  memorize doctor              Diagnose project and integration state',
    '  memorize update              Upgrade the CLI + refresh integrations machine-wide',
    '  memorize session activity    Show active sessions + their recent work',
    '  memorize consolidate         Run one memory-consolidation boundary now',
    '  memorize search <query>      Search project memory',
    '  memorize project show        Print bound project summary (JSON)',
    '  memorize version             Print the version of this binary',
    '',
    'Explicit coordination (optional — ambient memory works without these):',
    '  memorize task create ...     Claim a piece of work explicitly',
    '  memorize task list           List explicitly created tasks',
    '  memorize task resume         Load startup context for the current task',
    '  memorize task handoff ...    Record a handoff to the next agent',
    '',
    'Setup (usually run by the AI assistant):',
    '  memorize setup               Detect installed agents + wire global integration',
    '  memorize project setup       Bind cwd + import AGENTS.md / CLAUDE.md / rules',
    '  memorize project clone ...   Replica-clone a remote project into a fresh dir',
    '  memorize install claude      Wire Memorize into .claude/settings.local.json',
    '  memorize install codex       Wire Memorize bootstrap into AGENTS.override.md',
    '  memorize memory import ...   Ingest agent-distilled memories (stdin JSON)',
    '',
    'Full reference (every command, flags, and failure modes):',
    '  https://github.com/shakystar/memorize/blob/main/AGENT_GUIDE.md',
    '',
    'Tip: run `memorize <command> --help` or see the link above for details.',
  ].join('\n');
}
