export function renderScaffoldUsage(): string {
  return [
    'Memorize — shared project memory for human + AI collaboration',
    '',
    'Day-to-day:',
    '  memorize doctor              Diagnose project and integration state',
    '  memorize update              Upgrade the CLI + refresh integrations machine-wide',
    '  memorize session activity    Show active sessions + their recent work',
    '  memorize consolidate         Run one memory-consolidation boundary now',
    '  memorize search <query>      Search project memory',
    '  memorize memory list         List the project current (valid) memories',
    '  memorize memory show <id>    Print a memory full text + metadata',
    '  memorize memory retract <id> Retract (tombstone) a memory (append-only, reversible)',
    '  memorize memory gc           Physically reclaim un-pushed retracted memories (--dry-run)',
    '  memorize memory revert --session <id>  Revert (retract) a session’s memories (--dry-run)',
    '  memorize project show        Print bound project summary (JSON)',
    '  memorize version             Print the version of this binary',
    '',
    'Explicit coordination (optional — ambient memory works without these):',
    '  memorize task create ...     Claim a piece of work explicitly',
    '  memorize task list           List explicitly created tasks',
    '  memorize task resume [<id>]  Load startup context (current task, or --task/<id> for another)',
    '  memorize task handoff ...    Record a handoff to the next agent',
    '  memorize task update ...     Correct a task title/note (append-only)',
    '  memorize task done ...       Mark a task complete (handoff_ready -> done)',
    '  memorize task cancel ...     Cancel a task (terminal, append-only)',
    '  memorize project decision list   List project decisions (accepted; --all for superseded)',
    '  memorize project decision show <id>  Print a single decision in full',
    '  memorize project decision add ...  Record a project decision',
    '  memorize project decision supersede ...  Correct/replace a recorded decision (append-only)',
    '  memorize conflict list       List open conflicts (JSON)',
    '  memorize conflict resolve <id> ... Resolve an open conflict',
    '',
    'Setup (usually run by the AI assistant):',
    '  memorize init                One-shot: bind cwd + import context + detect & wire agent(s)',
    '  memorize memory import ...   Ingest agent-distilled memories (stdin JSON)',
    '  memorize personal import ... Ingest personal (cross-project, never-synced) memories',
    '',
    'Joining a shared project (paste the URL from the Hub page):',
    '  memorize login <hub-url>     Authenticate this host to a Hub (once per host)',
    '  memorize clone <url>         Join a shared project into a fresh dir (remote + first pull)',
    '  memorize remote <url>        Attach THIS project to a Hub remote + first push/pull',
    '',
    'Sharing this project (workspace control plane on a Hub):',
    '  memorize workspace create    Mint a shared workspace for this project on the Hub',
    '  memorize workspace invite    Mint an invite token/URL (shown once, never re-served)',
    '  memorize workspace join ...  Join a workspace with an invite token',
    '  memorize workspace status    Show the workspace binding + your role',
    '  memorize workspace members   List members, roles, verified emails',
    '  memorize workspace promote|demote|remove <member>  Owner-only role management',
    '',
    'Setup escape hatches (advanced — `memorize init` covers the common case):',
    '  memorize setup               Detect installed agents + wire global integration only',
    '  memorize project setup       Bind cwd + import AGENTS.md / CLAUDE.md / rules',
    '  memorize project init        Create a fresh project binding (no import)',
    '  memorize project relocate    Rebind an existing project to a new path (after a move)',
    '  memorize project clone ...   Replica-clone a remote project into a fresh dir',
    '  memorize project encryption ...  Enable/show E2E payload encryption (enable|show|disable)',
    '  memorize auth login ...      Store a Hub token once per host (drop inline --token)',
    '  memorize install claude      Wire Memorize into .claude/settings.local.json',
    '  memorize install codex       Wire Memorize into ~/.codex/hooks.json + AGENTS.md',
    '',
    'Full reference (every command, flags, and failure modes):',
    '  https://github.com/shakystar/memorize/blob/main/AGENT_GUIDE.md',
    '',
    'Tip: run `memorize <command> --help` or see the link above for details.',
  ].join('\n');
}
